Acme\Bundle\AppBundle\Entity\Supplychaininfo:
    repositoryClass: Akeneo\Pim\Enrichment\Bundle\Doctrine\ORM\Repository\ReferenceDataRepository
    type: entity
    table: acme_reference_data_Supplychaininfo
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        sortOrder:
            type: integer
        name:
            type: string
            length: 255
        chaininfo:
            type: string
            length: 255
    lifecycleCallbacks: {  }
