extensions:
    pim-qualitydescription-edit-form:
        module: custom_entity/form/common/edit-form
        aclResourceId: acme_custom_qualitydescription_edit

    pim-qualitydescription-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-qualitydescription-edit-form
        targetZone: breadcrumbs
        config:
            tab: pim-menu-reference_data
            item: acme_custom-menu-reference_data-item-qualitydescription

    pim-qualitydescription-edit-form-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-qualitydescription-edit-form
        position: 1000

    pim-qualitydescription-edit-form-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-qualitydescription-edit-form
        targetZone: content
        position: 100

    pim-qualitydescription-edit-form-label:
        module: custom_entity/form/common/label
        parent: pim-qualitydescription-edit-form
        targetZone: title
        position: 100

    pim-qualitydescription-edit-form-secondary-actions:
        module: pim/form/common/secondary-actions
        parent: pim-qualitydescription-edit-form
        targetZone: buttons
        position: 50

    pim-qualitydescription-edit-form-delete:
        module: custom_entity/form/common/delete
        parent: pim-qualitydescription-edit-form-secondary-actions
        targetZone: secondary-actions
        position: 100
        config:
            route: pim_customentity_rest_delete
            routeParams:
                customEntityName: qualitydescription
            trans:
                title: acme_custom.message.confirmation.remove.qualitydescription
                container: pim_enrich.confirmation.delete_item
                success: pim_custom_entity.message.confirmation.removed
                fail: pim_custom_entity.error.removing
            redirect: pim_customentity_index

    pim-qualitydescription-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-qualitydescription-edit-form
        targetZone: buttons
        position: 120

    pim-qualitydescription-edit-form-state:
        module: pim/form/common/state
        parent: pim-qualitydescription-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-qualitydescription-edit-form-save:
        module: custom_entity/form/common/save-form
        parent: pim-qualitydescription-edit-form
        targetZone: buttons
        position: 0
        config:
            updateSuccessMessage: acme_custom.qualitydescription.info.update_successful
            updateFailureMessage: acme_custom.qualitydescription.info.update_failed
            notReadyMessage: acme_custom.qualitydescription.info.field_not_ready
            url: pim_customentity_rest_edit
            route_params:
                customEntityName: qualitydescription
            redirectAfter: pim_customentity_rest_get
            excludedProperties: []

    pim-qualitydescription-edit-form-properties-tab:
        module: pim/common/tab
        parent: pim-qualitydescription-edit-form-form-tabs
        targetZone: container
        position: 100
        config:
            label: 'pim_custom_entity.form.tab.properties.title'

    pim-qualitydescription-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-qualitydescription-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-qualitydescription-edit-form-history:
        module: pim/common/tab/history
        parent: pim-qualitydescription-edit-form-form-tabs
        targetZone: container
        position: 110
        config:
            class: qualitydescription
            title: 'pim_custom_entity.form.tab.history.title'

    pim-qualitydescription-edit-form-state:
        module: pim/form/common/state
        parent: pim-qualitydescription-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.group.title

    pim-qualitydescription-edit-form-properties:
        module: pim/common/simple-view
        parent: pim-qualitydescription-edit-form-properties-tab
        targetZone: self
        config:
            template: pim/template/form/tab/sections

    pim-qualitydescription-edit-form-properties-common:
        module: pim/common/simple-view
        parent: pim-qualitydescription-edit-form-properties
        targetZone: accordion
        position: 100
        config:
            template: pim/template/form/tab/section
            templateParams:
                sectionTitle: pim_custom_entity.form.tab.properties.section.common
                dropZone: content

    pim-qualitydescription-edit-form-properties-code:
        module: pim/form/common/fields/text
        parent: pim-qualitydescription-edit-form-properties-common
        targetZone: content
        position: 90
        config:
            fieldName: code
            label: acme_custom.qualitydescription.field.label.code
            required: true
            readOnly: true

    pim-qualitydescription-edit-form-properties-name:
        module: pim/form/common/fields/text
        parent: pim-qualitydescription-edit-form-properties-common
        targetZone: content
        position: 95
        config:
            fieldName: name
            label: acme_custom.qualitydescription.field.label.name
            required: true
            readOnly: false

    pim-qualitydescription-edit-description:
        module: pim/form/common/fields/text
        parent: pim-qualitydescription-edit-form-properties-common
        targetZone: content
        position: 100
        config:
            fieldName: description
            label: acme_custom.qualitydescription.field.label.description
